MY_APP_CONFIG_FILE := $(realpath $(lastword $(MAKEFILE_LIST)))
MY_APP_IJKPLAYER_ROOT := $(patsubst %/,%,$(dir $(MY_APP_CONFIG_FILE)))
MY_APP_ANDROID_ROOT := $(realpath $(MY_APP_IJKPLAYER_ROOT)/..)
$(info DEBUG: CONFIG_FILE=$(MY_APP_CONFIG_FILE))
$(info DEBUG: IJKPLAYER_ROOT=$(MY_APP_IJKPLAYER_ROOT))
$(info DEBUG: ANDROID_ROOT=$(MY_APP_ANDROID_ROOT))
all:
